# _config.yml
title: ideas.nodes.ro
description: "A simple landing page showcasing ideas and projects."
url: "https://ideas.nodes.ro"
baseurl: ""            # user-page → keep empty
theme: jekyll-theme-minima          # GitHub Pages default theme; swap if you like
